### ISSUE TITLE
Bad Request: Unknown Path

### ISSUE THREAD

**Issue by bbommarito** [tristandunn/pusher-fake#32]
I am trying to use PusherFake within Development environment. The server does start, as I have tested it in console it will fork off (And I see it running in ps) however whenever I make a request to Pusher I get the following error:

Bad request: Unknown path: /apps/app_id/events

I am using Thin for devleopment, Rails version 4.1.6

**Comment by hcatlin** [comment]
Hrrm... I'm still working through this...

**Comment by hcatlin** [comment]
Whoa, that require actually launches the server! That's... uhh... interesting.

**Comment by tristandunn** [comment]
@hcatlin I'm up for reorganizing it or improving the documentation if you have any suggestions. Just reopen if you do.

**Comment by hcatlin** [comment]
I've got a flight tomorrow, so I might just do that. This library has saved me hours of crap, so happy to pitch in instead of just bitching. ;)

**Comment by tristandunn** [comment]
> This library has saved me hours of crap, ...

Wonderful to hear.
