### ISSUE TITLE
pusher-fake specs not able get the triggers sent from a delayed_job

### ISSUE THREAD

**Issue by suhasg** [tristandunn/pusher-fake#41]
I have job running in background which triggers the pusher events to the home page of the application to show the status of the process.

When testing the process using rspec and pusher-fake, I see that the triggers are working for test which are directly coming from normal methods. But the triggers coming from job are not handled by the pusher-fake.

I exactly followed the way pusher-fake example's spes are written.

Let me know how this problem can be resolved.

**Comment by tristandunn** [comment]
I'm guessing the socket and web ports might be different for the job if it's in a separate process. By default it [automatically assigns available ports](https://github.com/tristandunn/pusher-fake/blob/master/lib/pusher-fake/configuration.rb#L40-L41), so you should try manually configuring them and ensuring they are set correctly for the job process as well.

**Comment by tristandunn** [comment]
Closing this out. Feel free to reopen if ensuring the ports are the same didn't help.

**Comment by jpalumickas** [comment]
I have the same problem in development. When I'm trying to use it with Delayed jobs or Rails console, they all have different ports and they cannot communicate each other.

**Comment by tristandunn** [comment]
@jpalumickas Have you tried assigning specific ports via configuration instead of allowing the automatic assignment?

**Comment by jpalumickas** [comment]
sure, but then I'm having an error about : port already is using

**Comment by tristandunn** [comment]
@jpalumickas You'll only want to run the fake once, similar to the Foreman case mentioned in [the README](https://github.com/tristandunn/pusher-fake#development-environment). And you'll have to assign the custom port to Pusher manually.

**Comment by jpalumickas** [comment]
Ah, I see now, thanks. But what about making a command to run a stand alone server then ?

```
pusher: bundle exec pusher-fake --port 12345
```

What do you think ?
