### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by anthonator** [tristandunn/pusher-fake#50]
When we were setting up `pusher-fake` for a recent project we ran into some issues that took a couple hours of debugging to uncover.

We kept getting "unknown protocol" SSL errors whenever we used `Pusher.trigger` in our tests. Turns out we needed to configure the Pusher client's `scheme` value to be `http` rather than `https`. `https` seems to be the default for `Pusher.scheme`.

It might be valuable to others if this was in the documentation.

**Comment by tristandunn** [comment]
Sorry for the trouble, and thanks for the heads up.

Perhaps the library should set [`Pusher.encrypted = false`](https://github.com/pusher/pusher-http-ruby/blob/a4b3b022af54ac11a4e9562e65b616b5cc0d261d/lib/pusher/client.rb#L104-L114) in the base setup and document it for the custom setup.

**Comment by tristandunn** [comment]
@anthonator Actually, could you provide a failing example or more details on how you can trigger the error? I'd like to add a test for it as well.

**Comment by tristandunn** [comment]
Since I couldn't recreate this error last year, and it looks like [it defaults to HTTP in master](https://github.com/pusher/pusher-http-ruby/blob/86e613ffb887d9e4d386b1cdc005dde1757449f6/lib/pusher/client.rb#L26-L29) currently, I'm going to close this issue. Let me know if you run into it again.
