### ISSUE TITLE
Rename to pusher-local?

### ISSUE THREAD

**Issue by jtwaleson** [tristandunn/pusher-fake#53]
This project is great! However, the name "fake" suggest it's stubbing responses and is not actually working. While trying it out I wasn't sure what to expect until I got it working and it proved to be a completely functional dev server that implements the pusher APIs :)

I think the README needs some love and a rename of the project could be updated. Just my 2 cents of course!

**Comment by tristandunn** [comment]
Thanks! I think fake is the correct term though.

> Fakes are objects that have working implementations, but not same as production one. Usually they take some shortcut and have simplified version of production code.
> — https://blog.pragmatists.com/test-doubles-fakes-mocks-and-stubs-1a7491dfa3da

See other libraries like [fake-s3](https://github.com/jubos/fake-s3), [fakeredis](https://github.com/guilleiguaran/fakeredis), and [fake_stripe](https://github.com/thoughtbot/fake_stripe).

And the core goal is to be used in tests, not in development. Having access in development makes sense though, to allow for easier debugging.

I'll take a look at your README changes soon.
