### ISSUE TITLE
Mock statsHost

### ISSUE THREAD

**Issue by fikrikarim** [tristandunn/pusher-fake#56]
Hi @tristandunn, first of all thank you very much for creating and maintaining this gem. This really helps our app to test Pusher correctly! Thanks a lot :)

One thing I noticed is that not all of the client request is mocked already. There's request to `statsHost` that aren't directed to local server. I mean that shouldn't be a great deal. But right now we're not using VCR yet and we try to avoid making a request to a remote server. I wonder if it's possible to redirect the `statsHost` to local too or are you intentionally leaving that part?

Thanks!

**Comment by tristandunn** [comment]
Looks like you can disable the `statsHost` usage with the `disableStats` option.

That should be as simple as providing the option to the `javascript` helper:

```erb
<%= PusherFake.javascript(disableStats: true) %>
```

Let me know if that helps! Also, I'll look into adding the host and disable options to the configuration, and defaulting to the stats being disabled.

**Comment by fikrikarim** [comment]
Oh I see. Yes that should help with our use case. I didn't know there's `disableStats` option. Thanks for the fast response Tristan :)

**Comment by tristandunn** [comment]
Awesome! Realized I forgot to link to [the client options page](https://pusher.com/docs/client_api_guide/client_connect#options_parameter).

**Comment by fikrikarim** [comment]
Cool man. Now I'm working on the chat feature using the [Pusher Chatkit](https://pusher.com/chatkit), and I miss this gem already 👍

**Comment by tristandunn** [comment]
Glad to hear it's helpful!

And maybe I should look into Chatkit support, or a creating a new library. I'd hope that a lot of it is just functionally built on top of the existing Pusher implementation.

**Comment by tristandunn** [comment]
@fikrikarim Released a new version with the `disableStats` configuration in it.

**Comment by fikrikarim** [comment]
@tristandunn got it thanks @tristandunn !
