### ISSUE TITLE
Support Cached Channels

### ISSUE THREAD

**Issue by ScottPierce** [tristandunn/pusher-fake#70]
Cached channels recently came out. What's preventing me from using them right now is that this library doesn't have support for them.

https://pusher.com/docs/channels/using_channels/cache-channels/

**Comment by tristandunn** [comment]
Thanks for letting me know.

I have [a branch](https://github.com/tristandunn/pusher-fake/compare/td-cache-channels) implementing them if you want to try it out. I'll probably won't be able to verify and release until next week.

**Comment by ScottPierce** [comment]
Wow - you're on top of it man! You are also going to implement the webhook events, like `cache_miss`?

**Comment by tristandunn** [comment]
Forgot about those the other day, but just pushed them with tests to the same branch.

Do you have a project you can try the branch out on? Would be curious how they work in the real-world right now.

**Comment by ScottPierce** [comment]
Yes - but I use this project compiled into a docker image. The system I have setup to do that deals with releases of this project. Are there any releases with this?

**Comment by tristandunn** [comment]
I just release [v4.1.0](https://rubygems.org/gems/pusher-fake/versions/4.1.0) with cache channels. Thanks again for reporting it, and let me know if you run into any issues.

**Comment by ScottPierce** [comment]
awesome! I'll give it a shot
