### ISSUE TITLE
SSL/TLS Support from command line

### ISSUE THREAD

**Issue by jtwaleson** [tristandunn/pusher-fake#72]
Is SSL/TLS supported when running the pusher-fake binary? The documentation on secure mode is a bit sparse. Once I figure out how to run it I can create a PR with the documentation.

**Comment by jtwaleson** [comment]
So you mean like a configuration file that gets loaded?

Alternatively, would you be open to including the list of options as described here? 

https://www.rubydoc.info/github/eventmachine/eventmachine/EventMachine/Connection:start_tls

Changing the underlying library could cause potential problems in the future, but the list of options is very standard for SSL setups and seems stable since a long time.

**Comment by tristandunn** [comment]
> So you mean like a configuration file that gets loaded?

Correct. Although thinking about it more I don't think I like that idea either. See below.

> Alternatively, would you be open to including the list of options as described here?

Even with the options being somewhat standard I think I'd still prefer not to.

The library is meant to be used mostly in testing, and possibly in development, which should rarely require SSL. If it's necessary to have locally all the time, I'd prefer the binary be created in the project that needs it and updated to enable SSL there.

**Comment by jtwaleson** [comment]
Ok, makes sense. The reason I need secure sockets in dev mode is for
privileged access to webcam and microphone. My product has a phone connect
to a laptop using pusher over a local network (in dev mode). Without https
the microphone and webcam don’t work. With https, pusher goes for wss://
automatically.

I’ll try to get it to work and send a PR with an example in the readme once
I figure it out.

Thanks!
